name: Demo Workflow 2
on: workflow_dispatch

env:
  OS_NAME: Ubuntu Machine

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
      - name: Capture VM info
        run: | 
          echo "USERNAME=$(whoami)" >> GITHUB_ENV
          echo "OS_INFO=${NAME} ${VERSION}" >> $GITHUB_ENV          
          echo "USER_ID=$(id -u)" >> GITHUB_ENV
          echo "WORK_DIR=$(pwd)" >> GITHUB_ENV
      - name: Make File
        run: |
          echo "Artifact_upload: -e OS: $OS_NAME" -e user: $USERNAME, USERID: $USER_ID -e Working directory: $WORK_DIR >> artifact_upload
      - name: Upload Artifact 
        uses: actions/upload-artifact@v7
        with:
          name: Artifact Upload
          path: |
            artifact_upload