name: Demo Workflow 2

run-name: "${{ github.ref_name }} - Run #${{ github.run_number }}"

on:
  workflow_dispatch:

env:
  OS_NAME: Ubuntu Machine

jobs:
  gather-data:
    runs-on: ubuntu-latest

    steps:
      - name: Capture VM info
        run: |
          source /etc/os-release

          echo "USERNAME=$(whoami)" >> $GITHUB_ENV
          echo "OS_INFO=${NAME} ${VERSION}" >> $GITHUB_ENV
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Make File
        run: |
          echo -e "Branch: ${{ github.ref_name }}\nRun Number: ${{ github.run_number }}\nOS: $OS_INFO\nUser: $USERNAME\nUser ID: $USER_ID\nWorking Directory: $WORK_DIR" > artifact_upload

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Artifact Upload
          path: artifact_upload